"""empty message

Revision ID: 06035d126cd3
Revises: 5afadb6a6d63
Create Date: 2018-08-07 19:54:14.701725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06035d126cd3'
down_revision = '5afadb6a6d63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Float(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('sensor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    # ### end Alembic commands ###
